# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:10:59+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    AlimwCertificatePostRequest,
    AlimwCertificatePostResponse,
    AlimwCertificatePostResponse1,
    AlimwCertificatePostResponse2,
    AlimwCertificatePostResponse3,
    AlimwCertificatePostResponse4,
    AlimwCertificatePostResponse5,
    AlimwCertificatePostResponse6,
    AlsblCertificatePostRequest,
    AlsblCertificatePostResponse,
    AlsblCertificatePostResponse1,
    AlsblCertificatePostResponse2,
    AlsblCertificatePostResponse3,
    AlsblCertificatePostResponse4,
    AlsblCertificatePostResponse5,
    AlsblCertificatePostResponse6,
    AlsfcCertificatePostRequest,
    AlsfcCertificatePostResponse,
    AlsfcCertificatePostResponse1,
    AlsfcCertificatePostResponse2,
    AlsfcCertificatePostResponse3,
    AlsfcCertificatePostResponse4,
    AlsfcCertificatePostResponse5,
    AlsfcCertificatePostResponse6,
    ApptuCertificatePostRequest,
    ApptuCertificatePostResponse,
    ApptuCertificatePostResponse1,
    ApptuCertificatePostResponse2,
    ApptuCertificatePostResponse3,
    ApptuCertificatePostResponse4,
    ApptuCertificatePostResponse5,
    ApptuCertificatePostResponse6,
    ClcerCertificatePostRequest,
    ClcerCertificatePostResponse,
    ClcerCertificatePostResponse1,
    ClcerCertificatePostResponse2,
    ClcerCertificatePostResponse3,
    ClcerCertificatePostResponse4,
    ClcerCertificatePostResponse5,
    ClcerCertificatePostResponse6,
    NooclCertificatePostRequest,
    NooclCertificatePostResponse,
    NooclCertificatePostResponse1,
    NooclCertificatePostResponse2,
    NooclCertificatePostResponse3,
    NooclCertificatePostResponse4,
    NooclCertificatePostResponse5,
    NooclCertificatePostResponse6,
    SrcerCertificatePostRequest,
    SrcerCertificatePostResponse,
    SrcerCertificatePostResponse1,
    SrcerCertificatePostResponse2,
    SrcerCertificatePostResponse3,
    SrcerCertificatePostResponse4,
    SrcerCertificatePostResponse5,
    SrcerCertificatePostResponse6,
)

app = MCPProxy(
    description="Department of Labour Resources (http://labour.bih.nic.in/) issues various certificates to the citizens. They can be pulled into citizen's DigiLocker account. Currently available- Shops and Commercial Establishments Registration Certificate",
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Labour Resource Department, Bihar',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/labourbih/v3'}],
)


@app.post(
    '/alimw/certificate',
    description=""" API to verify Application for License for Inter State Migrant Workmen. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def alimw(body: AlimwCertificatePostRequest = None):
    """
    Application for License for Inter State Migrant Workmen
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/alsbl/certificate',
    description=""" API to verify Application/ License for Boilers. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def alsbl(body: AlsblCertificatePostRequest = None):
    """
    Application/ License for Boilers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/alsfc/certificate',
    description=""" API to verify Application/ License for Factory. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def alsfc(body: AlsfcCertificatePostRequest = None):
    """
    Application/ License for Factory
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/apptu/certificate',
    description=""" API to verify Application realted to Trade Unions. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def apptu(body: ApptuCertificatePostRequest = None):
    """
    Application realted to Trade Unions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/clcer/certificate',
    description=""" API to verify Registration Certificate for Contract Labour License. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def clcer(body: ClcerCertificatePostRequest = None):
    """
    Registration Certificate for Contract Labour License
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/noocl/certificate',
    description=""" API to verify Notice of Closure. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def noocl(body: NooclCertificatePostRequest = None):
    """
    Notice of Closure
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/srcer/certificate',
    description=""" API to verify Registration Certificate of Shops And Commercial Establishment. """,
    tags=['certificate_application_processing'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def srcer(body: SrcerCertificatePostRequest = None):
    """
    Registration Certificate of Shops And Commercial Establishment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
